### ISSUE TITLE
Go client version 1

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore-Client-Go#42]
The Go client needs to support the common features between the dotnet, rust, nodejs and java clients in order for the first supported version to be released.

- [x] Streams:
  - [x] Reading
    - [x] ReadStreamEvents
    - [x] ReadAllEvents
  - [x] AppendToStream
  - [x] Deletions:
    - [x] DeleteStream
    - [x] TombstoneStream
  - [x] Subscriptions (streams/$all)
    - [x] SubscribeToStream
    - [x] SubscribeToAll
    - [x] SubscribeToAllFiltered
- [x] Discovery:
  - [x] Gossip Seed
  - [x] Host Names
  - [x] Single Node
  - [x] Node reconnections
- [x] Persistent Subscriptions:
  - [x] Creating/Updating/Deleting
  - [x] Subscribing

Additionally, the client should have:

- [x] Logging
- [x] Connection String support
- [x] Doc samples

**Comment by YoEight** [comment]
We still need to release a patched release of version 1 and that issue could be closed.

**Comment by YoEight** [comment]
Done
